---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: freebsd-10.2

suites:
  - name: default
    run_list:
      - recipe[b-nginx]
    attributes:
      b-nginx:
        site:
          domain: "webapp.sb.com"
          backend_port: "8484"
          app_servers: [ "192.168.33.35","192.168.33.36" ]

  - name: ubuntu
    run_list:
      - recipe[b-nginx::deb]
    attributes:
      b-nginx:
        site:
          domain: "webapp.sb.com"

  - name: rhel
    run_list:
      - recipe[b-nginx::rhel]
    attributes:
      b-nginx:
        site:
          domain: "webapp.sb.com"
